name: DynamicPriceShop
version: 1.0
main: com.dhwogur.dynamicpriceshop.DynamicPriceShop
api-version: 1.20
description: "예시용 동적 가격 플러그인 – 온라인으로 만든 첫 플러그인"
author: YourName

commands:
  helloworld:
    description: "플러그인 정상 로드 확인용 테스트 명령어"
    usage: /<command>