name: DynamicPriceShop
main: com.yourname.dynamicpriceshop.DynamicPriceShop
version: 1.0.0
api-version: 1.21
depend: [Vault]        # Vault가 없으면 플러그인이 로드되지 않음
commands:
  shop:
    description: 상점 GUI를 엽니다.
    usage: /shop
    permission: dynamicpriceshop.use
    permission-message: §c이 명령을 사용할 권한이 없습니다.